##-- py21cmnet ancillary config --##
# Combined with autoencoder3d.yaml
# these are default parameters
# for conv_layer, encode, and decode

conv_layer :
  conv : 'Conv3d'
  conv_kwargs : 
    kernel_size : 3
    padding : 1
    padding_mode : 'circular'
  activation : 'ReLU'
  act_kwargs : {}
  batch_norm : 'BatchNorm3d'
  norm_kwargs : {}
  dropout : None
  dropout_kwargs : {}

encode : 
  pool : 'MaxPool3d'
  pool_kwargs :
    kernel_size : 2

decode :
  up_mode : 'ConvTranspose3d'
  up_kwargs :
    kernel_size : 3
    stride : 2
    padding : 1
    output_padding : 1


