##-- py21cmnet primary config --##
# A depth-2 autoencoder with skip connections
# Operates on Nd data ombined with *_defaults.yaml
# See py21cmnet.utils.load_autoencoder_params()

encode0 :
  conv_layers :
    - conv_kwargs : 
        in_channels : 2
        out_channels : 12
    - conv_kwargs : 
        in_channels : 12
        out_channels : 12

encode1 : 
  conv_layers :
    - conv_kwargs : 
        in_channels : 12
        out_channels : 24
    - conv_kwargs : 
        in_channels : 24
        out_channels : 24

decode0 : 
  conv_layers :
    - conv_kwargs : 
          in_channels : 24
          out_channels : 48
    - conv_kwargs : 
          in_channels : 48
          out_channels : 48
  up_kwargs : 
    in_channels : 48
    out_channels : 24

decode1 : 
  conv_layers :
    - conv_kwargs : 
          in_channels : 48
          out_channels : 24
    - conv_kwargs : 
          in_channels : 24
          out_channels : 24
  up_kwargs :
    in_channels : 24
    out_channels : 12

decode2 : 
  conv_layers :
    - conv_kwargs : 
          in_channels : 24
          out_channels : 12
    - conv_kwargs : 
          in_channels : 12
          out_channels : 12
    - conv_kwargs : 
          in_channels : 12
          out_channels : 2
          kernel_size : 1
          padding : 0
  up_mode : None

connections : {1: 1, 2: 0}

final_transforms :
  - 'ModifiedSigmoid': {c: 2}
  - 'Softplus'
